title: ImageXD
description: Image processing across domains
sitename: ImageXD
url: 'http://www.imagexd.org'
baseurl: '/2017'
sass:
  sass_dir: /assets/_sass
  style: :compressed
markdown: kramdown
kramdown:
    input: GFM
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
